# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-19 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_comment_like', '0002_auto_20150828_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='five_stars',
            field=models.IntegerField(choices=[(1, 'First'), (3, 'Second'), (3, 'Third'), (4, 'Four'), (5, 'Five')], default=3, null=True),
        ),
    ]
