# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-07 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_comment_like', '0004_auto_20171206_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='five_stars',
            field=models.IntegerField(choices=[(1, 'First'), (3, 'Second'), (3, 'Third'), (4, 'Four'), (5, 'Five')], default=3, null=True),
        ),
    ]
